name: build

on:
  release:
    types:
      - "published"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v16.20.0
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm run build

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/scmtble/zhifou-web:latest,registry.cn-hangzhou.aliyuncs.com/scmtble/zhifou-web:${{ env.RELEASE_VERSION }}